import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations = {
  zh: {
    // General
    'app.title': 'CMRI平台',
    'app.logout': '退出',
    'common.save': '保存',
    'common.loading': '加载中...',
    'common.refresh': '刷新',
    'common.confirm': '确认',
    'common.cancel': '取消',
    'common.success': '成功',
    'common.error': '错误',
    'common.yes': '是',
    'common.no': '否',
    'common.slice': '切片',
    'common.no_data': '无数据',
    'common.no_images': '无图像',
    'common.view': '视图',
    'common.clear': '清除',
    'tool.measure': '测量工具',
    'tool.measure_hint': '点击并拖动以测量距离',
    
    // Auth
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.username': '用户名',
    'auth.password': '密码',
    'auth.confirm_password': '确认密码',
    'auth.login_failed': '登录失败',
    'auth.error_generic': '发生错误，请重试',
    'auth.no_account': '没有账号？',
    'auth.has_account': '已有账号？',
    'auth.passwords_mismatch': '密码不匹配',
    'auth.registration_failed': '注册失败',
    
    // Sidebar
    'sidebar.patient_list': '患者列表',
    'sidebar.segmentation': '分割标注',
    'sidebar.cardiac_annotation': '4CH 影像标注',
    'sidebar.functional': '量化评估',
    'sidebar.structure': '结构与功能评估',
    'sidebar.other_findings': '其他影像所见',
    'sidebar.lge': 'LGE分析',
    'sidebar.analysis': '图像质量评估',
    'sidebar.experiment': '实验结果',
    'sidebar.cardiac': '心脏诊断',
    'sidebar.evaluation': '报告评分',
    'sidebar.stats': '统计分析',
    'sidebar.settings': '设置',
    'sidebar.dashboard': '仪表盘',
    'sidebar.data': '数据管理',
    'sidebar.model': '模型训练',
    'sidebar.hospital_browser': '医院数据浏览',
    
    // Segmentation
    'seg.sample_list': '样本列表',
    'seg.sequences': '序列',
    'seg.select_sample': '请选择样本',
    'seg.select_hint': '请选择样本和序列以开始标注',
    'seg.no_more_samples': '没有更多样本了',
    'seg.unsaved_changes_warning': '您有未保存的标注，确定要离开吗？未保存的更改将丢失。',
    
    // Patient Manager
    'patient.manager': '患者管理',
    'patient.search_placeholder': '搜索患者ID...',
    'patient.search_placeholder_full': '搜索患者ID或数据集...',
    'patient.no_match': '无匹配患者',
    'patient.select_hint': '请从左侧列表选择患者及功能模块',
    'patient.id': '患者ID',
    'patient.dataset': '数据集',
    'patient.action': '操作',
    'patient.completed': '已完成',
    'patient.incomplete': '未完成',
    
    // Structure Assessment
    'structure.title': '结构与功能评估',
    'structure.q1_title': '问题 1：左心室 LV 心肌厚度',
    'structure.lv_wall_thickness': 'LV 室壁',
    'structure.normal': '正常',
    'structure.normal_desc': '左心室壁未见明显增厚或变薄',
    'structure.thickened': '增厚',
    'structure.thinned': '变薄',
    
    'structure.thickened_type': '增厚类型',
    'structure.concentric': '向心性',
    'structure.eccentric': '偏心性',
    'structure.asymmetric': '不对称性',
    'structure.prominent_at': '部位 [具体部位] 为著',
    'structure.prominent_at_paren': '（具体部位）为著',
    'structure.max_thickness': '最大舒张末期厚度 [具体数值] mm',
    'structure.max_thickness_paren': '最大舒张末期厚度（具体数值）mm',
    
    'structure.thinned_type': '变薄类型',
    'structure.diffuse': '弥漫',
    'structure.local': '局部',
    
    'structure.increased_trabeculation': '增多肌小梁',
    'structure.outflow_obstruction': '流出道梗阻',
    'structure.yes': '是',
    'structure.no': '否',
    
    'structure.q2_title': '问题 2：心脏运动及功能',
    'structure.lv_wall_motion': 'LV 室壁运动',
    'structure.enhanced': '增强',
    'structure.reduced': '减弱',
    'structure.paradoxical': '矛盾运动',
    'structure.location': '部位 [具体部位]',
    
    'structure.aneurysm': '室壁瘤',
    'structure.aneurysm_none': '无',
    'structure.aneurysm_true': '真性',
    'structure.aneurysm_pseudo': '假性',
    
    'structure.q3_title': '问题 3：瓣膜形态及功能',
    'structure.valvular_morphology': '瓣膜形态',
    'structure.mitral_stenosis': '二尖瓣狭窄',
    'structure.tricuspid_stenosis': '三尖瓣狭窄',
    'structure.aortic_stenosis': '主动脉瓣狭窄',
    
    'structure.valvular_regurgitation': '瓣膜返流',
    'structure.mitral_regurgitation': '二尖瓣返流',
    'structure.tricuspid_regurgitation': '三尖瓣返流',
    'structure.aortic_regurgitation': '主动脉瓣返流',
    'structure.mild': '轻度',
    'structure.moderate': '中度',
    'structure.severe': '重度',
    'structure.none': '无',

    // Other Findings
    'other_findings.title': '其他影像所见',
    'other_findings.fat_infiltration': '心肌内脂肪浸润',
    'other_findings.location': '部位',
    'other_findings.specific_location': '具体部位',
    'other_findings.thrombus': '血栓',
    'other_findings.size': '大小',
    'other_findings.mobility': '活动度',
    'other_findings.pericardial_effusion': '心包积液',
    'other_findings.pe.trace': '微量（3-4mm）',
    'other_findings.pe.small': '少量积液（5-14mm）',
    'other_findings.pe.moderate': '中量积液（15-24mm）',
    'other_findings.pe.large': '大量积液（≥25mm）',
    'other_findings.pleural_effusion': '胸腔积液',
    'other_findings.describe_if_present': '描述（如有）',
    'other_findings.other': '其他',
    'other_findings.specific_description': '具体描述',

    // Functional Assessment
    'func.title': '功能与结构评估',
    'func.lv_title': '一、左心室功能与结构',
    'func.rv_title': '二、右心室功能与结构',
    'func.atrial_title': '三、心房功能与形态',
    'func.lvef': 'LVEF：左心室射血分数评估',
    'func.lvedv': 'LVEDV：左心室舒张末期容积评估',
    'func.lvedd': 'LVEDD：左心室舒张末期内径评估',
    'func.ivs': 'IVS：室间隔厚度评估',
    'func.rvef': 'RVEF：右心室射血分数评估',
    'func.rvedv': 'RVEDV：右心室舒张末期容积评估',
    'func.lav': 'LAV：左心房容积评估',
    'func.rav': 'RAV：右心房容积评估',
    
    // Functional Options
    'func.opt.significantly_decreased': '显著降低',
    'func.opt.decreased': '降低',
    'func.opt.normal': '正常',
    'func.opt.increased': '升高',
    'func.opt.significantly_increased': '显著升高',
    'func.opt.significantly_enlarged': '显著扩大',
    'func.opt.enlarged': '扩大',
    'func.opt.significantly_shrunk': '显著缩小',
    'func.opt.shrunk': '缩小',
    'func.opt.significantly_thickened': '显著增厚',
    'func.opt.thickened': '增厚',
    'func.opt.significantly_thinned': '显著变薄',
    'func.opt.thinned': '变薄',
    
    // Lesion Detection
    'lesion.title': '病灶检查',
    'lesion.mode_label': '标注模式:',
    'lesion.mode_lesion': '病灶 (Lesion)',
    'lesion.mode_ref': '参考 (Ref)',
    'lesion.marked_areas': '已标记区域',
    'lesion.drag_hint': '在影像上拖拽画框...',
    'lesion.q1': '1. 是否存在高信号？',
    'lesion.q2': '2. 高信号强度是否穿透？',
    'lesion.transmural_label': '是否穿透？',
    'lesion.box_lesion': '病灶区域',
    'lesion.box_reference': '参考区域',
    'lesion.si_mean': '平均信号',
    'lesion.ratio': '比率',
    'lesion.save_success': '病灶检查结果保存成功',
    
    // Image Analysis
    'analysis.title': '图像分析',
    'analysis.original': '原始图像',
    'analysis.enhanced': '增强视图',
    'analysis.contrast_btn': '对比视图 (AI Enhanced)',
    'analysis.q1': '1. 是否存在卷叠伪影？',
    'analysis.q2': '2. 是否存在呼吸伪影？',
    'analysis.q3': '3. 是否存在血流/流动伪影？',
    'analysis.q4': '4. 是否存在金属伪影？',
    'analysis.q5': '5. 是否存在运动伪影？',
    'analysis.draw_hint': '请在图中框出伪影区域',
    'analysis.drawing': '标注中...',
    'analysis.click_to_draw': '点击标注',
    'analysis.no_boxes': '暂无标注，请在左侧图像上框选',
    'analysis.save_success': '图像分析结果保存成功',
    'analysis.drawing_active': '标注模式已激活',
    'analysis.cine_play': '播放',
    'analysis.cine_pause': '暂停',
    'common.delete': '删除',
    
    // Evaluation
    'eval.waiting_list': '待诊病例',
    'eval.has_report': '已生成报告',
    'eval.no_report': '无报告',
    'eval.detail_title': '病例详情',
    'eval.dataset': '数据集',
    'eval.path': '路径',
    'eval.report_title': '诊断报告',
    'eval.no_report_content': '暂无报告内容',
    'eval.keyframes': '关键帧',
    'eval.scoring_title': '结果评分',
    'eval.score_label': '评分 (0-100)',
    'eval.coverage': '临床覆盖度',
    'eval.consistency': '事实一致性',
    'eval.hallucination': '幻觉率 (5=无, 1=高)',
    'eval.score_placeholder': '输入0-100的分数',
    'eval.comment_label': '修改意见 / 备注',
    'eval.comment_placeholder': '请输入具体的修改意见...',
    'eval.submit_btn': '提交评分',
    'eval.submit_success': '评分提交成功',
    'eval.score_guide': '评分标准参考：',
    'eval.guide.90': '90-100分: 优秀 (诊断准确，描述清晰)',
    'eval.guide.80': '80-89分: 良好 (诊断准确，轻微瑕疵)',
    'eval.guide.60': '60-79分: 及格 (核心正确，细节遗漏)',
    'eval.guide.less60': '<60分: 不及格 (关键诊断错误)',

    // Statistics
    'stats.title': '工作量统计',
    'stats.overview': '整体概览',
    'stats.module': '功能模块',
    'stats.total_cases': '总病例数',
    'stats.completed': '已完成',
    'stats.incomplete': '未完成',
    'stats.completion_rate': '完成率',
    'stats.view_details': '查看详情',
    'stats.case_list': '病例列表',
    'stats.case_id': '病例ID',
    'stats.dataset': '数据集',
    'stats.status': '状态',
  },
  en: {
    // General
    'app.title': 'CMRI Platform',
    'app.initializing': 'Initializing application...',
    'app.init_error': 'Error initializing application:',
    'app.logout': 'Logout',
    'common.save': 'Save',
    'common.loading': 'Loading...',
    'common.refresh': 'Refresh',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.slice': 'Slice',
    'common.no_data': 'No Data',
    'common.no_images': 'No Images',
    'common.view': 'View',
    'common.clear': 'Clear',
    'tool.measure': 'Measure Tool',
    'common.feature_dev': 'Feature under development...',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.username': 'Username',
    'auth.password': 'Password',
    'auth.confirm_password': 'Confirm Password',
    'auth.login_failed': 'Login failed',
    'auth.error_generic': 'An error occurred. Please try again.',
    'auth.no_account': "Don't have an account?",
    'auth.has_account': 'Already have an account?',
    'auth.passwords_mismatch': 'Passwords do not match',
    'auth.registration_failed': 'Registration failed',
    
    // Sidebar
    'sidebar.patient_list': 'Patient List',
    'sidebar.segmentation': 'Segmentation',
    'sidebar.cardiac_annotation': '4CH Annotation',
    'sidebar.functional': 'Quantitative Assessment',
    'sidebar.structure': 'Structure',
    'sidebar.other_findings': 'Other Imaging Findings',
    'sidebar.lge': 'LGE Analysis',
    'sidebar.analysis': 'Image Analysis',
    'sidebar.experiment': 'Experiments',
    'sidebar.cardiac': 'Cardiac Diag',
    'sidebar.evaluation': 'Report Scoring',
    'sidebar.settings': 'Settings',
    'sidebar.dashboard': 'Dashboard',
    'sidebar.data': 'Data Management',
    'sidebar.model': 'Model Training',
    'sidebar.hospital_browser': 'Hospital Browser',
    
    // Experiment
    'experiment.stats_table': 'Statistics Table (cardiac_metrics_statistics2.xlsx)',
    'experiment.load_error': 'Failed to load experiment results',
    
    // Segmentation
    'seg.sample_list': 'Sample List',
    'seg.sequences': 'Sequences',
    'seg.select_sample': 'Select Sample',
    'seg.select_hint': 'Select sample and sequence to start segmentation',
    'seg.no_more_samples': 'No more samples!',
    'seg.unsaved_changes_warning': 'You have unsaved annotations. Leave anyway? Unsaved changes will be lost.',
    
    // Patient Manager
    'patient.manager': 'Patient Manager',
    'patient.search_placeholder': 'Search Patient ID...',
    'patient.search_placeholder_full': 'Search Patient ID or Dataset...',
    'patient.no_match': 'No matches found',
    'patient.select_hint': 'Select a patient and module from the left list',
    'patient.id': 'Patient ID',
    'patient.dataset': 'Dataset',
    'patient.action': 'Action',
    
    // Structure Assessment
    'structure.title': '结构与功能评估',
    'structure.q1_title': '问题 1：左心室 LV 心肌厚度',
    'structure.lv_wall_thickness': 'LV 室壁',
    'structure.normal': '正常',
    'structure.normal_desc': '左心室壁未见明显增厚或变薄',
    'structure.thickened': '增厚',
    'structure.thinned': '变薄',
    
    'structure.thickened_type': '增厚类型',
    'structure.concentric': '向心性',
    'structure.eccentric': '偏心性',
    'structure.asymmetric': '不对称性',
    'structure.prominent_at': '部位 [具体部位] 为著',
    'structure.prominent_at_paren': '（具体部位）为著',
    'structure.max_thickness': '最大舒张末期厚度 [具体数值] mm',
    'structure.max_thickness_paren': '最大舒张末期厚度（具体数值）mm',
    
    'structure.thinned_type': '变薄类型',
    'structure.diffuse': '弥漫',
    'structure.local': '局部',
    
    'structure.increased_trabeculation': '增多肌小梁',
    'structure.outflow_obstruction': '流出道梗阻',
    'structure.yes': '是',
    'structure.no': '否',
    
    'structure.q2_title': '问题 2：心脏运动及功能',
    'structure.lv_wall_motion': 'LV 室壁运动',
    'structure.enhanced': '增强',
    'structure.reduced': '减弱',
    'structure.paradoxical': '矛盾运动',
    'structure.location': '部位 [具体部位]',
    
    'structure.aneurysm': '室壁瘤',
    'structure.aneurysm_none': '无',
    'structure.aneurysm_true': '真性',
    'structure.aneurysm_pseudo': '假性',
    
    'structure.q3_title': '问题 3：瓣膜形态及功能',
    'structure.valvular_morphology': '瓣膜形态',
    'structure.mitral_stenosis': '二尖瓣狭窄',
    'structure.tricuspid_stenosis': '三尖瓣狭窄',
    'structure.aortic_stenosis': '主动脉瓣狭窄',
    
    'structure.valvular_regurgitation': '瓣膜返流',
    'structure.mitral_regurgitation': '二尖瓣返流',
    'structure.tricuspid_regurgitation': '三尖瓣返流',
    'structure.aortic_regurgitation': '主动脉瓣返流',
    'structure.mild': '轻度',
    'structure.moderate': '中度',
    'structure.severe': '重度',
    'structure.none': 'None',

    // Other Findings
    'other_findings.title': 'Other Imaging Findings',
    'other_findings.fat_infiltration': 'Intramyocardial Fat Infiltration',
    'other_findings.location': 'Location',
    'other_findings.specific_location': 'Specific location',
    'other_findings.thrombus': 'Thrombus',
    'other_findings.size': 'Size',
    'other_findings.mobility': 'Mobility',
    'other_findings.pericardial_effusion': 'Pericardial Effusion',
    'other_findings.pe.trace': 'Trace (3-4mm)',
    'other_findings.pe.small': 'Small (5-14mm)',
    'other_findings.pe.moderate': 'Moderate (15-24mm)',
    'other_findings.pe.large': 'Large (≥25mm)',
    'other_findings.pleural_effusion': 'Pleural Effusion',
    'other_findings.describe_if_present': 'Describe if present',
    'other_findings.other': 'Other',
    'other_findings.specific_description': 'Specific description',

    // Functional Assessment
    'func.title': 'Functional & Structural Assessment',
    'func.lv_title': 'I. LV Function & Structure',
    'func.rv_title': 'II. RV Function & Structure',
    'func.atrial_title': 'III. Atrial Function & Morphology',
    'func.lvef': 'LVEF: Left Ventricular Ejection Fraction',
    'func.lvedv': 'LVEDV: LV End-Diastolic Volume',
    'func.lvedd': 'LVEDD: LV End-Diastolic Dimension',
    'func.ivs': 'IVS: Interventricular Septum Thickness',
    'func.rvef': 'RVEF: Right Ventricular Ejection Fraction',
    'func.rvedv': 'RVEDV: RV End-Diastolic Volume',
    'func.lav': 'LAV: Left Atrial Volume',
    'func.rav': 'RAV: Right Atrial Volume',
    
    // Functional Options
    'func.opt.significantly_decreased': 'Significantly Decreased',
    'func.opt.decreased': 'Decreased',
    'func.opt.normal': 'Normal',
    'func.opt.increased': 'Increased',
    'func.opt.significantly_increased': 'Significantly Increased',
    'func.opt.significantly_enlarged': 'Significantly Enlarged',
    'func.opt.enlarged': 'Enlarged',
    'func.opt.significantly_shrunk': 'Significantly Shrunk',
    'func.opt.shrunk': 'Shrunk',
    'func.opt.significantly_thickened': 'Significantly Thickened',
    'func.opt.thickened': 'Thickened',
    'func.opt.significantly_thinned': 'Significantly Thinned',
    'func.opt.thinned': 'Thinned',
    
    // Lesion Detection
    'lesion.title': 'Lesion Detection',
    'lesion.mode_label': 'Mode:',
    'lesion.mode_lesion': 'Lesion',
    'lesion.mode_ref': 'Reference',
    'lesion.marked_areas': 'Marked Areas',
    'lesion.drag_hint': 'Drag to draw boxes on image...',
    'lesion.q1': '1. Is there high signal intensity?',
    'lesion.q2': '2. Is the high signal transmural?',
    'lesion.transmural_label': 'Transmural?',
    'lesion.save_success': 'Lesion detection saved successfully',
    'lesion.box_lesion': 'Lesion Box',
    'lesion.box_reference': 'Reference Box',
    'lesion.si_mean': 'SI Mean',
    'lesion.ratio': 'Ratio',
    
    // Image Analysis
    'analysis.title': 'Image Analysis',
    'analysis.original': 'Original',
    'analysis.enhanced': 'Enhanced',
    'analysis.contrast_btn': 'Contrast View (AI Enhanced)',
    'analysis.q1': '1. Aliasing Artifact?',
    'analysis.q2': '2. Respiratory Artifact?',
    'analysis.q3': '3. Flow Artifact?',
    'analysis.q4': '4. Metal Artifact?',
    'analysis.q5': '5. Motion Artifact?',
    'analysis.draw_hint': 'Please draw box around artifact',
    'analysis.drawing': 'Drawing...',
    'analysis.click_to_draw': 'Click to Draw',
    'analysis.no_boxes': 'No annotations yet',
    'analysis.save_success': 'Analysis saved successfully',
    
    // Evaluation
    'eval.waiting_list': 'Waiting List',
    'eval.has_report': 'Report Ready',
    'eval.no_report': 'No Report',
    'eval.detail_title': 'Case Detail',
    'eval.dataset': 'Dataset',
    'eval.path': 'Path',
    'eval.report_title': 'Diagnosis Report',
    'eval.no_report_content': 'No report content available',
    'eval.keyframes': 'Key Frames',
    'eval.scoring_title': 'Scoring',
    'eval.score_label': 'Score (0-100)',
    'eval.coverage': 'Clinical Coverage',
    'eval.consistency': 'Factual Consistency',
    'eval.hallucination': 'Hallucination Rate (5=None, 1=High)',
    'eval.score_placeholder': 'Enter score 0-100',
    'eval.comment_label': 'Comments',
    'eval.comment_placeholder': 'Enter specific comments...',
    'eval.submit_btn': 'Submit Score',
    'eval.submit_success': 'Score submitted successfully',
    'eval.score_guide': 'Score Guide:',
    'eval.guide.90': '90-100: Excellent (Accurate diagnosis, clear description)',
    'eval.guide.80': '80-89: Good (Accurate diagnosis, minor flaws)',
    'eval.guide.60': '60-79: Pass (Core correct, details missing)',
    'eval.guide.less60': '<60: Fail (Critical diagnosis error)',

    // Statistics
    'stats.title': 'Workload Statistics',
    'stats.overview': 'Overview',
    'stats.module': 'Module',
    'stats.total_cases': 'Total Cases',
    'stats.completed': 'Completed',
    'stats.incomplete': 'Incomplete',
    'stats.completion_rate': 'Completion Rate',
    'stats.view_details': 'View Details',
    'stats.case_list': 'Case List',
    'stats.case_id': 'Case ID',
    'stats.dataset': 'Dataset',
    'stats.status': 'Status',
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('zh');

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
